spring:
  application:
    name: cimenterprise-eurekaserver
  profiles:
    active: apigateway
    
    
---
#API Gateway profile
spring:
  profiles: apigateway  

server:
  port: 8761

management:
    security:
      enabled: false
      
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
    
  server:
    waitTimeInMsWhenSyncEmpty: 0
    
    
---
#API Gateway profile
spring:
  profiles: uiserver
  
server:
  port: 8762

management:
    security:
      enabled: false
      
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
    
  server:
    waitTimeInMsWhenSyncEmpty: 0
